version: '2'

services:
    crossdock:
        image: crossdock/crossdock
        links:
            - go
            - java
            - python

        environment:
            - WAIT_FOR=go,java,python

            - AXIS_CLIENT=go
            - AXIS_S1NAME=go,java,python
            - AXIS_SAMPLED=true,false
            - AXIS_S2NAME=go,java,python
            - AXIS_S2TRANSPORT=http,tchannel
            - AXIS_S3NAME=go,java,python
            - AXIS_S3TRANSPORT=http,tchannel

            - BEHAVIOR_TRACE=client,s1name,sampled,s2name,s2transport,s3name,s3transport

            - REPORT=compact
    go:
        build: .
        ports:
            - "8080-8082"

    java:
        image: jaegertracing/xdock-java
        ports:
            - "8080-8082"

    python:
        image: jaegertracing/xdock-py
        ports:
            - "8080:8082"

#    node:
#        image: yarpc/yarpc-node
#        ports:
#            - "8080-8082"
#
#    python-sync:
#        image: yarpc/yarpc-python
#        ports:
#            - 8080
#        environment:
#            - SYNC=1
