name: FOSSA
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  oss-license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.x"
      - name: Setup GOPATH
        uses: ./.github/actions/setup-gopath
      - name: run FOSSA analysis
        env:
          # FOSSA Push-Only API Token
          FOSSA_API_KEY: '304657e2357ba57b416b94e6b119131b'
        run: |
          cd $PROJECT
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          fossa init
          fossa analyze
