name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Install tools
      run: make install-ci USE_DEP=true

    - name: Run tests
      run: make test-ci

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: cover.out
        fail_ci_if_error: true
        verbose: true
