name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    env:
      GOPATH: /go
      PROJECT: /go/src/github.com/uber/jaeger-client-go

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Install tools
      run: |
        export GOPATH=${{env.GOPATH}}
        export PROJECT=${{env.PROJECT}}
        mkdir -p $GOPATH
        export PATH=$PATH:$(go env GOPATH)/bin
        echo $PATH
        mkdir -p $(dirname $PROJECT)
        ln -s $(pwd) $PROJECT
        cd $PROJECT
        make install-ci USE_DEP=true
        dep version

    - name: Run tests
      run: |
        export GOPATH=${{env.GOPATH}}
        export PROJECT=${{env.PROJECT}}
        cd $PROJECT
        make test-ci

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: cover.out
        fail_ci_if_error: true
        verbose: true
